### ISSUE TITLE
Cambiar data de endpoint en organization

### ISSUE THREAD

**Issue by YonPalac1** [alkemyTech/OT139-SERVER#46]
El link de la imagen que está en el endpoint de organization lleva a la carpeta de la imagen, pero no a la imagen en si:
Cambiar por:
https://lh4.googleusercontent.com/8d2ci9rICYB3X3es_CKLJPtRugK-Mi-ThEqcSVYBqFJLj0nAwv0kJharSZLWl24X4Y-KAYQ3MWqdJw=w1366-h643

**Comment by AndresHense** [comment]
ayer quedamos en el discord en guardar la imagen en la carpeta publica de la parte cliente y que la string de imagen del endpoint tenga el path de la imagen en el cliente
