### ISSUE TITLE
Algunas Seed no funcionan correctamente

### ISSUE THREAD

**Issue by evarelaavalos** [alkemyTech/OT139-SERVER#48]
## Descripción del Problema
Estos mensajes de error me tiraron despues de correr el comando `npx sequelize-cli db:seed:all`.

### create-demo-user

![SX_20220315_172357_Code](https://user-images.githubusercontent.com/45970652/158657610-d535fe48-261a-4b21-83cf-6cb942605f47.jpg)

### create-activities

![SX_20220315_172638_Code](https://user-images.githubusercontent.com/45970652/158657749-1054d6bd-86ac-4522-96b4-5b8e7b753bbd.jpg)

**Comment by AndresHense** [comment]
una vez que esten pulleados los cambios hay que actualizar la tabla con:
```bash
npx sequelize-cli db:drop
npx sequelize-cli db:create
npx sequelize-cli db:migrate
npx sequelize-cli db:seed:all
```
